/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a1i9NBBHzOs
 */
import { Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Mailcard } from "./MailCard"

export default function Mailbox() {
  return (
    (<div key="1" className="lg:grid lg:grid-cols-2 h-screen">
      <div className="dark:bg-[#3D3D3D] h-full overflow-auto">
        <div className="p-6 space-y-6">
          <h1 className="text-3xl font-bold">Your Mails</h1>
          <div className="space-y-4">
            <Mailcard />
            {/* <Card className="p-4 flex flex-col bg-white">
              <div className="flex justify-between items-center mb-2">
                <div className="flex items-center space-x-4">
                  <Image alt="User Image" src="/avatar.png" height={40} width={40} className="rounded-full" />
                  <div className="font-medium">John Doe</div>
                </div>
                <Badge className="bg-[#D4AF37] text-white">New</Badge>
              </div>
              <div className="text-gray-700 dark:text-gray-300">
                This is a preview of the letter content. Click to expand.
              </div>
            </Card> */}
            <Card className="p-4 flex flex-col bg-white">
              <div className="flex justify-between items-center mb-2">
                <div className="flex items-center space-x-2">
                  <Avatar alt="User Image" src="/placeholder.svg?height=40&width=40" />
                  <div className="font-medium">Jane Doe</div>
                </div>
                <Badge className="bg-[#D4AF37] text-white">New</Badge>
              </div>
              <div className="text-gray-700 dark:text-gray-300">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor,
                dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula
                massa, varius a, semper congue, euismod non, mi. Proin porttitor, orci nec nonummy molestie, enim est
                eleifend mi, non fermentum diam nisl sit amet erat. Duis semper. Duis arcu massa, scelerisque vitae,
                consequat in, pretium a, enim. Pellentesque congue. Ut in risus volutpat libero pharetra tempor. Cras
                vestibulum bibendum augue. Praesent egestas leo in pede. Praesent blandit odio eu enim. Pellentesque sed
                dui ut augue blandit sodales. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
                cubilia Curae; Aliquam nibh. Mauris ac mauris sed pede pellentesque fermentum. Maecenas adipiscing ante
                non diam sodales hendrerit.
              </div>
            </Card>
          </div>
        </div>
      </div>
      <div className="bg-[#F5F1ED] dark:bg-[#1F1F1F] p-6 h-full overflow-auto">
        <div className="space-y-4">
          <h2 className="text-2xl font-bold">Write a Letter</h2>
          <Textarea className="w-full h-96" placeholder="Write your letter here..." />
          <Button className="w-full">Send Letter</Button>
        </div>
      </div>
    </div>)
  );
}
