version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./private/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./private/private.key:/etc/nginx/ssl/private.key
    depends_on:
      - backend
      - frontend
    networks:
      - mailex_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.local
    image: ytlitw/mailex-backend
    networks:
      - mailex_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_IP: ${NEXT_PUBLIC_BACKEND_IP}
    image: ytlitw/mailex-frontend
    env_file:
      - frontend/.env.local
    networks:
      - mailex_network

networks:
  mailex_network:
    driver: bridge
