/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hlP72O3fLFG
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Avatar } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"

export function Homepage() {
  return (
    (<div key="1" className="bg-[#FFFAF0] dark:bg-[#3B2922] h-screen">
      <nav
        className="flex justify-around items-center bg-[#F5DEB3] dark:bg-[#73563D] py-4 px-6 shadow-md">
        <IconAccountcircle className="text-[#8B4513] dark:text-[#FFDEAD] text-2xl" />
        <IconMailoutline className="text-[#8B4513] dark:text-[#FFDEAD] text-2xl" />
        <Link className="text-[#8B4513] dark:text-[#FFDEAD] font-bold" href="#">
          Find a penpal
        </Link>
      </nav>
      <section className="w-full py-12 flex justify-center">
        <div className="container grid gap-6 md:gap-8 px-4 md:px-6">
          <div className="flex justify-center items-center mb-6">
            <div className="relative w-2/3">
              <Input
                className="border border-[#8B4513] dark:border-[#FFDEAD] rounded-md px-4 py-2 w-full"
                placeholder="Search"
                type="text" />
              <IconSearch
                className="absolute right-8 top-1/2 transform -translate-y-1/2 text-[#8B4513] dark:text-[#FFDEAD]" />
              <Button
                className="absolute right-0 top-1/2 transform -translate-y-1/2 text-[#8B4513] dark:text-[#FFDEAD] border-[#8B4513] dark:border-[#FFDEAD]"
                variant="outline">
                <IconFilterlist className="text-[#8B4513] dark:text-[#FFDEAD]" />
              </Button>
            </div>
          </div>
          <Card
            className="group hover:bg-[#F5DEB3] dark:hover:bg-[#73563D] transition-colors relative">
            <div className="p-4 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <IconAccountcircle className="text-[#8B4513] dark:text-[#FFDEAD] text-2xl" />
                <Avatar
                  alt="Avatar"
                  className="w-12 h-12 rounded-full"
                  src="/placeholder.svg?height=50&width=50" />
                <div>
                  <h3 className="text-lg font-semibold text-[#8B4513] dark:text-[#FFDEAD]">
                    John Doe
                    <span className="text-sm text-[#8B4513] dark:text-[#FFDEAD]">New York</span>
                  </h3>
                  <p
                    className="text-sm text-[#8B4513] dark:text-[#FFDEAD] overflow-ellipsis overflow-hidden max-w-xs whitespace-nowrap">
                    Hello, how are you? I hope you are doing well...
                  </p>
                </div>
              </div>
              <p className="text-xs text-[#8B4513] dark:text-[#FFDEAD]">10:30 AM</p>
            </div>
          </Card>
          <Card
            className="group hover:bg-[#F5DEB3] dark:hover:bg-[#73563D] transition-colors relative">
            <div className="p-4 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <IconAccountcircle className="text-[#8B4513] dark:text-[#FFDEAD] text-2xl" />
                <Avatar
                  alt="Avatar"
                  className="w-12 h-12 rounded-full"
                  src="/placeholder.svg?height=50&width=50" />
                <div>
                  <h3 className="text-lg font-semibold text-[#8B4513] dark:text-[#FFDEAD]">
                    Jane Doe
                    <span className="text-sm text-[#8B4513] dark:text-[#FFDEAD]">Los Angeles</span>
                  </h3>
                  <p
                    className="text-sm text-[#8B4513] dark:text-[#FFDEAD] overflow-ellipsis overflow-hidden max-w-xs whitespace-nowrap">
                    Good morning! I hope today is a good day for you...
                  </p>
                </div>
              </div>
              <p className="text-xs text-[#8B4513] dark:text-[#FFDEAD]">09:15 AM</p>
            </div>
          </Card>
          <Card
            className="group hover:bg-[#F5DEB3] dark:hover:bg-[#73563D] transition-colors relative">
            <div className="p-4 flex items-center justify-between">
              <div className="flex items-center gap-4">
                <IconAccountcircle className="text-[#8B4513] dark:text-[#FFDEAD] text-2xl" />
                <Avatar
                  alt="Avatar"
                  className="w-12 h-12 rounded-full"
                  src="/placeholder.svg?height=50&width=50" />
                <div>
                  <h3 className="text-lg font-semibold text-[#8B4513] dark:text-[#FFDEAD]">
                    Alex Smith
                    <span className="text-sm text-[#8B4513] dark:text-[#FFDEAD]">Chicago</span>
                  </h3>
                  <p
                    className="text-sm text-[#8B4513] dark:text-[#FFDEAD] overflow-ellipsis overflow-hidden max-w-xs whitespace-nowrap">
                    Can we meet? I&apos;d like to discuss something important...
                  </p>
                </div>
              </div>
              <p className="text-xs text-[#8B4513] dark:text-[#FFDEAD]">Yesterday</p>
            </div>
          </Card>
        </div>
      </section>
    </div>)
  );
}


function IconAccountcircle(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
    </svg>)
  );
}


function IconMailoutline(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}


function IconFilterlist(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M7 12h10" />
      <path d="M10 18h4" />
    </svg>)
  );
}


function IconSearch(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
